spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true

#  # 发送者开启 confirm 确认机制
#  spring.rabbitmq.publisher-confirms=true
#  # 发送者开启 return 确认机制
#  spring.rabbitmq.publisher-returns=true
#  ####################################################
#  # 设置消费端手动 ack
#  spring.rabbitmq.listener.simple.acknowledge-mode=manual
#  # 是否支持重试
#  spring.rabbitmq.listener.simple.retry.enabled=true

mybatis:
  config-location: classpath:db/mybatis/config.xml



